### PR TITLE
Add additional dangerous apps packages

### PR DESCRIPTION
**Pull request by Fi5t**

### CODE REVIEW

**Comment by stealthcopter** [comment]
Looks good to me, thanks!

**Comment by WuglyakBolgoink** [comment]
related to https://gist.github.com/WuglyakBolgoink/024ef1faaab070122292d7520213fbad

**Comment by WuglyakBolgoink** [comment]
@stealthcopter 

FYI: https://gist.github.com/karandpr/2abf38642e9e4753d03eb44177727f50#gistcomment-3379045

**Comment by Zhuinden** [comment]
Some of these apps listed don't seem to have anything to do with Root.

For example, the app "mobilism", "blackmart", and even lucky patcher (see https://github.com/scottyab/rootbeer/issues/94) don't seem to have anything to do with root.

That means if using this library, this would generate false positives regarding rooting, despite the library being used in banking apps. I see this as an effort to update from 0.0.7 to 0.1.0, but I will need to adjust this list in the fork that'll actually be used.

**Pull request merged**
