### PR TITLE
Support for Android TV devices

### PR DESCRIPTION
**Pull request by deepakpk009**
For supporting Android TV devices I have done the following:
1. Enabled landscape mode 
2. Set default focus to fab button

### CODE REVIEW

**Comment by stealthcopter** [comment]
All looks good here, LGTM @scottyab you agree?

@deepakpk009 Is there any chance you could provide a screenshot or two of rootbeer running on a TV? just so we can upload it to google play. Thanks!

**Comment by deepakpk009** [comment]
> All looks good here, LGTM @scottyab you agree?
> 
> @deepakpk009 Is there any chance you could provide a screenshot or two of rootbeer running on a TV? just so we can upload it to google play. Thanks!

Sure will send the screenshots

**Comment by deepakpk009** [comment]
device-2020-03-11-144644
device-2020-03-11-144716
device-2020-03-11-144736

**Comment by stealthcopter** [comment]
@deepakpk009 cheers you rock!

**Pull request merged**
