### PR TITLE
tasty beer ui commit

### PR DESCRIPTION
**Pull request by andyb129**
messed up the last pull request but this one should be easy as no crossing of the git streams (and no conflicts to merge i think?)!  As I said before not sure about the red icon and colour scheme but just let me know if you wanna change it. Cheers, Andy.

### CODE REVIEW

**Comment by scottyab** [comment]
Thanks for this @andyb129, could you remove the `.iml` files and any files under  `.idea` folder this these should of been defined in `.gitignores`

**Comment by scottyab** [comment]
The UI reports incorrect results (or at least it looks wrong red crosses) when the device is passing.

**Comment by andyb129** [comment]
OK fixed the messed up logic in this pull request and removed .idea files.  Also updated .gitignore 👍

**Comment by scottyab** [comment]
Thanks @andyb129

**Pull request merged**
